MapName: PVP Default Config
cubeMaxX: 205
cubeMinX: 92
cubeMaxZ: 360
cubeMinZ: 245
ActiveForceField: Y
GameMode: freeforall
KillsToWinGame: 25
SecondsToEndGame: 600
EnlightenChance: 10
LobbySawn:
  X: 150
  Y: 113
  Z: 321
Inventory:
  Armor:
    Helmet:
      Name: LEATHER_HELMET
      NumEnchants: 0
      Enchant1:
        ID: 1
        Level: 4
    ChestPlate:
      Name: LEATHER_CHESTPLATE
      NumEnchants: 0
    Leggings:
      Name: LEATHER_LEGGINGS
      NumEnchants: 0
    Boots:
      Name: LEATHER_BOOTS
      NumEnchants: 0
  NumItems: 5
  Item1:
    Name: STONE_SWORD
    Amount: 1
    Damage: 0
    NumEnchants: 0
    Enchant1:
      ID: 16
      Level: 3
  Item2:
    Name: BOW
    Amount: 1
    Damage: 0
    NumEnchants: 0
  Item3:
    Name: STONE_PICKAXE
    Amount: 1
    Damage: 0
    NumEnchants: 0
  Item4:
    Name: COOKED_FISH
    Amount: 16
    Damage: 1
    NumEnchants: 0
  Item5:
    Name: ARROW
    Amount: 64
    Damage: 0
    NumEnchants: 0
  NumPotions: 1
  Potion1: 
    Type: POISON
    Amount: 1
    Level: 1
    Splash: Y
  NumSpecials: 0
  Special1: COMPASS
  NumEffects: 0
  Effect1:
    Name: SPEED
    Duration: 200000
    Amplifier: 1
NumTeams: 4
Team1: 
  Name: Red
  Armor:
    Color:
      R: 255
      G: 0
      B: 0
  ChatColor: RED
Team2:
  Name: Green
  Armor:
    Color:
      R: 0
      G: 255
      B: 0
  ChatColor: GREEN
Team3:
  Name: Blue
  Armor:
    Color:
      R: 0
      G: 0
      B: 255
  ChatColor: BLUE
Team4:
  Name: Yellow
  Armor:
    Color:
      R: 255
      G: 255
      B: 0
  ChatColor: YELLOW
NumSpawnPoints: 12
RespawnPoint1:
  X: 190
  Y: 29
  Z: 313
  Yaw: -39
RespawnPoint2:
  X: 173
  Y: 38
  Z: 316
  Yaw: 180
RespawnPoint3:
  X: 136
  Y: 29
  Z: 340
  Yaw: 51
RespawnPoint4:
  X: 132
  Y: 38
  Z: 325
  Yaw: 224
RespawnPoint5:
  X: 109
  Y: 29
  Z: 291
  Yaw: 141
RespawnPoint6:
  X: 126
  Y: 38
  Z: 288
  Yaw: -4
RespawnPoint7:
  X: 163
  Y: 29
  Z: 264
  Yaw: -127
RespawnPoint8:
  X: 167
  Y: 38
  Z: 279
  Yaw: 47
RespawnPoint9:
  X: 163
  Y: 48
  Z: 290
  Yaw: 47
RespawnPoint10:
  X: 164
  Y: 48
  Z: 313
  Yaw: 129
RespawnPoint11:
  X: 136
  Y: 48
  Z: 314
  Yaw: 227
RespawnPoint12:
  X: 135
  Y: 48
  Z: 291
  Yaw: 310
NumWeapons: 4
Weapon1:
  X: 185
  Y: 34
  Z: 266
  Name: IRON_SWORD
  Amount: 1
  Damage: 0
  DisplayName: Cold Steel
  SpawnInterval: 30
  NumEnchants: 0
Weapon2:
  X: 189
  Y: 33
  Z: 335
  Name: IRON_AXE
  Amount: 1
  Damage: 0
  DisplayName: Shiny Axe
  SpawnInterval: 30
  NumEnchants: 1
  Enchant1:
    ID: 16
    Level: 2
Weapon3:
  X: 114
  Y: 33
  Z: 338
  Name: BLAZE_ROD
  Amount: 1
  Damage: 0
  DisplayName: Hot Stick
  SpawnInterval: 15
  NumEnchants: 1
  Enchant1:
    ID: 20
    Level: 2    
Weapon4:
  X: 110
  Y: 33
  Z: 269
  Name: CLAY_BRICK
  Amount: 1
  Damage: 0
  DisplayName: Heavy Brick
  SpawnInterval: 20
  NumEnchants: 2
  Enchant1:
    ID: 19
    Level: 2
  Enchant2:
    ID: 16
    Level: 1
Weapon5:
  X: 149
  Y: 44
  Z: 302
  Name: BOW
  Amount: 1
  Damage: 0
  DisplayName: SpudOfGun
  SpawnInterval: 40
  NumEnchants: 1
  Enchant1:
    ID: 50
    Level: 1   