MapName: PVP Default Config
cubeMaxX: 205
cubeMinX: 92
cubeMaxZ: 360
cubeMinZ: 245
ActiveForceField: Y
GameMode: freeforall
KillsToWinGame: 25
SecondsToEndGame: 600
EnlightenChance: 10
LobbySawn:
  X: 150
  Y: 113
  Z: 321
Inventory:
  Armor:
    Helmet:
      Name: LEATHER_HELMET
      NumEnchants: 0
      Enchant1:
        ID: 1
        Level: 4
    ChestPlate:
      Name: LEATHER_CHESTPLATE
      NumEnchants: 0
    Leggings:
      Name: LEATHER_LEGGINGS
      NumEnchants: 0
    Boots:
      Name: LEATHER_BOOTS
      NumEnchants: 0
  NumItems: 5
  Item1:
    Name: STONE_SWORD
    Amount: 1
    Damage: 0
    NumEnchants: 0
    Enchant1:
      ID: 16
      Level: 3
  Item2:
    Name: BOW
    Amount: 1
    Damage: 0
    NumEnchants: 0
  Item3:
    Name: STONE_PICKAXE
    Amount: 1
    Damage: 0
    NumEnchants: 0
  Item4:
    Name: COOKED_FISH
    Amount: 16
    Damage: 1
    NumEnchants: 0
  Item5:
    Name: ARROW
    Amount: 64
    Damage: 0
    NumEnchants: 0
  NumPotions: 1
  Potion1: 
    Type: POISON
    Amount: 1
    Level: 1
    Splash: Y
  NumSpecials: 0
  Special1: COMPASS
  NumEffects: 0
  Effect1:
    Name: SPEED
    Duration: 200000
    Amplifier: 1
NumTeams: 4
Team1: 
  Name: Red
  Armor:
    Color:
      R: 255
      G: 0
      B: 0
  ChatColor: RED
Team2:
  Name: Green
  Armor:
    Color:
      R: 0
      G: 255
      B: 0
  ChatColor: GREEN
Team3:
  Name: Blue
  Armor:
    Color:
      R: 0
      G: 0
      B: 255
  ChatColor: BLUE
Team4:
  Name: Yellow
  Armor:
    Color:
      R: 255
      G: 255
      B: 0
  ChatColor: YELLOW
NumSpawnPoints: 3
RespawnPoint1:
  X: 135
  Y: 44
  Z: 280
  Yaw: 43
RespawnPoint2:
  X: 160
  Y: 48
  Z: 293
  Yaw: 48
RespawnPoint3:
  X: 178
  Y: 38
  Z: 312
  Yaw: -151
NumWeapons: 0
Weapon1:
  X: 160
  Y: 70
  Z: 291
  Name: IRON_SWORD
  Amount: 1
  Damage: 0
  NumEnchants: 0
  Enchant1:
    ID: 16
    Level: 3